//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaWEB.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ctaWEB.App_GlobalResources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Char Site Ever.
        /// </summary>
        public static string Best_Chart_Ever {
            get {
                return ResourceManager.GetString("Best_Chart_Ever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer sitio argentino en brindarte herramientas chartistas para el mercado local e internacional..
        /// </summary>
        public static string Best_Chart_EverText {
            get {
                return ResourceManager.GetString("Best_Chart_EverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguinos en las redes sociales.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguí nuestras publicaciones, compartí tus charts e interactuá con otros usuarios..
        /// </summary>
        public static string FollowUs_Text {
            get {
                return ResourceManager.GetString("FollowUs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayúdanos a construir VICIOUSS.
        /// </summary>
        public static string HelpUs {
            get {
                return ResourceManager.GetString("HelpUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro objetivo es darte todas las herramientas que necesites para el análisis de tus inversiones, ayúdanos a brindarlas..
        /// </summary>
        public static string HelpUs_Text {
            get {
                return ResourceManager.GetString("HelpUs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invierta en sus Inversiones.
        /// </summary>
        public static string Invest_Investments {
            get {
                return ResourceManager.GetString("Invest_Investments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porque el éxito de tus inversiones depende del tiempo que le dediques..
        /// </summary>
        public static string Invest_InvestmentsText {
            get {
                return ResourceManager.GetString("Invest_InvestmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Tenés Preguntas ?.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envíanos tu consulta acerca de lo que sea y te responderemos cuanto antes..
        /// </summary>
        public static string Questions_Text {
            get {
                return ResourceManager.GetString("Questions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrese Ahora.
        /// </summary>
        public static string Register_Now {
            get {
                return ResourceManager.GetString("Register_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y comience a disfrutar!!!.
        /// </summary>
        public static string Start_Enjoy {
            get {
                return ResourceManager.GetString("Start_Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERACTUA CON LOS CREADORES DE VICIOUSS.
        /// </summary>
        public static string Viciouss_Creators {
            get {
                return ResourceManager.GetString("Viciouss_Creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Viciouss.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus Análisis Bien Resguardados.
        /// </summary>
        public static string Well_Saved_Analysis {
            get {
                return ResourceManager.GetString("Well_Saved_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestras​ bases de datos conservarán tus análisis para un mejor track de tus inversiones..
        /// </summary>
        public static string Well_Saved_AnalysisText {
            get {
                return ResourceManager.GetString("Well_Saved_AnalysisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con VICIOUSS podrás:.
        /// </summary>
        public static string With_Viciouss {
            get {
                return ResourceManager.GetString("With_Viciouss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizar análisis técnico de activos argentinos durante la rueda..
        /// </summary>
        public static string With_Viciouss1 {
            get {
                return ResourceManager.GetString("With_Viciouss1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construir tus propios Watchlists..
        /// </summary>
        public static string With_Viciouss2 {
            get {
                return ResourceManager.GetString("With_Viciouss2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizar un seguimiento ágil de tus activos favoritos desde cualquier dispositivo..
        /// </summary>
        public static string With_Viciouss3 {
            get {
                return ResourceManager.GetString("With_Viciouss3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir tus análisis en las redes sociales..
        /// </summary>
        public static string With_Viciouss4 {
            get {
                return ResourceManager.GetString("With_Viciouss4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dar tu feedback para mejorar tu experiencia y adaptar el sitio a tus necesidades..
        /// </summary>
        public static string With_Viciouss5 {
            get {
                return ResourceManager.GetString("With_Viciouss5", resourceCulture);
            }
        }
    }
}
