//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ctaDBEntities : DbContext
    {
        public ctaDBEntities()
            : base("name=ctaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<Market_Quote> Market_Quote { get; set; }
        public virtual DbSet<MarketIndex> MarketIndexes { get; set; }
        public virtual DbSet<MarketIndex_Quote> MarketIndex_Quote { get; set; }
        public virtual DbSet<MarketIndex_Stock> MarketIndex_Stock { get; set; }
        public virtual DbSet<MercadoPagoNotification> MercadoPagoNotifications { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Portfolio_Stock> Portfolio_Stock { get; set; }
        public virtual DbSet<Portfolio_Stock_Indicator> Portfolio_Stock_Indicator { get; set; }
        public virtual DbSet<Portfolio_Stock_Shape> Portfolio_Stock_Shape { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Report_Type> Report_Type { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Stock_Quote> Stock_Quote { get; set; }
        public virtual DbSet<Stock_Quote_Intradiary> Stock_Quote_Intradiary { get; set; }
        public virtual DbSet<Stock_Report> Stock_Report { get; set; }
        public virtual DbSet<Stock_Type> Stock_Type { get; set; }
        public virtual DbSet<TashScheduleErrorLog> TashScheduleErrorLogs { get; set; }
        public virtual DbSet<TaskSchedule> TaskSchedules { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<Tenant_Type> Tenant_Type { get; set; }
        public virtual DbSet<VcssTask> VcssTasks { get; set; }
        public virtual DbSet<VcssTaskInfo> VcssTaskInfoes { get; set; }
        public virtual DbSet<VcssTaskLog> VcssTaskLogs { get; set; }
    
        public virtual ObjectResult<GetCarouselQuotesByMarketID_Result> GetCarouselQuotesByMarketID(Nullable<int> marketID)
        {
            var marketIDParameter = marketID.HasValue ?
                new ObjectParameter("marketID", marketID) :
                new ObjectParameter("marketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCarouselQuotesByMarketID_Result>("GetCarouselQuotesByMarketID", marketIDParameter);
        }
    }
}
