//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicator()
        {
            this.Portfolio_Stock_Indicator = new HashSet<Portfolio_Stock_Indicator>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<bool> active { get; set; }
        public string param1 { get; set; }
        public string color1 { get; set; }
        public string param2 { get; set; }
        public string color2 { get; set; }
        public string param3 { get; set; }
        public string color3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Stock_Indicator> Portfolio_Stock_Indicator { get; set; }
    }
}
