//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MercadoPagoNotification
    {
        public int Id { get; set; }
        public string obj_id { get; set; }
        public Nullable<bool> live_mode { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string user_id { get; set; }
        public string api_version { get; set; }
        public string action { get; set; }
        public string data_id { get; set; }
        public string data_content { get; set; }
    }
}
