//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Stock_Shape
    {
        public int Id { get; set; }
        public int portfolio_id { get; set; }
        public int stock_id { get; set; }
        public int shape_id { get; set; }
        public string color { get; set; }
        public System.DateTime date1 { get; set; }
        public double value1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<double> value2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<double> value3 { get; set; }
        public string name { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual Shape Shape { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
