//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Stock_Indicator
    {
        public int Id { get; set; }
        public int portfolio_id { get; set; }
        public int stock_id { get; set; }
        public int indicator_id { get; set; }
        public string param1 { get; set; }
        public string color1 { get; set; }
        public string param2 { get; set; }
        public string color2 { get; set; }
        public string param3 { get; set; }
        public string color3 { get; set; }
    
        public virtual Indicator Indicator { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
