//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public bool active { get; set; }
        public int type { get; set; }
    
        public virtual Report_Type Report_Type { get; set; }
    }
}
