//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Report
    {
        public int Id { get; set; }
        public int Stock_ID { get; set; }
        public double Price { get; set; }
        public System.DateTime Date_Round { get; set; }
        public Nullable<double> MA20 { get; set; }
        public Nullable<double> MA50 { get; set; }
        public Nullable<double> MA200 { get; set; }
        public Nullable<double> RSI14 { get; set; }
        public Nullable<double> Momentum12 { get; set; }
        public Nullable<double> SOFast_k14 { get; set; }
        public Nullable<double> SOFast_d3 { get; set; }
        public Nullable<double> MACD2612 { get; set; }
        public Nullable<double> MA9 { get; set; }
        public Nullable<double> EMA20 { get; set; }
        public Nullable<double> EMA12 { get; set; }
        public Nullable<double> EMA26 { get; set; }
        public Nullable<double> BoolUP { get; set; }
        public Nullable<double> BoolLOW { get; set; }
        public Nullable<double> WilliansR { get; set; }
        public Nullable<double> RSI14UpsAvg { get; set; }
        public Nullable<double> RSI14DownsAvg { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
