//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Quote_Intradiary
    {
        public int Id { get; set; }
        public int stock_id { get; set; }
        public double opening { get; set; }
        public double prev_closing { get; set; }
        public double ask { get; set; }
        public double ask_size { get; set; }
        public double bid { get; set; }
        public double bid_size { get; set; }
        public double change { get; set; }
        public double change_percent { get; set; }
        public string last_trade_time { get; set; }
        public double last_trade_price { get; set; }
        public decimal last_trade_size { get; set; }
        public System.DateTime last_trade_date { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
