//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Quote
    {
        public int Id { get; set; }
        public int stock_id { get; set; }
        public double opening { get; set; }
        public double closing { get; set; }
        public double minimun { get; set; }
        public double maximun { get; set; }
        public decimal volume { get; set; }
        public System.DateTime date_round { get; set; }
        public double adj_close { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
