//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VcssTask
    {
        public int Id { get; set; }
        public int vcss_task_info_id { get; set; }
        public System.DateTime scheduled_time { get; set; }
        public string data { get; set; }
    
        public virtual VcssTaskInfo VcssTaskInfo { get; set; }
    }
}
