//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VcssTaskInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VcssTaskInfo()
        {
            this.VcssTasks = new HashSet<VcssTask>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> market_id { get; set; }
        public string url { get; set; }
        public string auth_token { get; set; }
        public System.DateTime last_updated { get; set; }
        public int step { get; set; }
    
        public virtual Market Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VcssTask> VcssTasks { get; set; }
    }
}
