//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctaDATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VcssTaskLog
    {
        public int Id { get; set; }
        public string task_name { get; set; }
        public string task_data { get; set; }
        public System.DateTime task_scheduled_time { get; set; }
        public string action { get; set; }
        public string error_msg { get; set; }
        public System.DateTime error_time { get; set; }
    }
}
